version: '3.8'

services:
  postgres_container:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: railway
      POSTGRES_PASSWORD: railway
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - postgres_container
    command: >
      sh -c "python manage.py migrate &&
             python manage.py loaddata postgres_data.json &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DATABASE_HOST=postgres_container
      - DATABASE_NAME=db
      - DATABASE_USER=railway
      - DATABASE_PASSWORD=railway
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
